### ISSUE TITLE
setting to slide the panes vertically

### ISSUE THREAD

**Issue by manogna4** [deathau/sliding-panes-obsidian#23] opened 2020-11-11 07:20 UTC
My obsidian window is usually taller than it is wide, so having panes slide up-down instead of left-right would be very useful. It would also make titles easier to read

**Comment by deathau** [comment] 2020-11-12 05:07
I agree with this.
However, I'm closing this issue as a duplicate of #14 as this is the purpose for that one

**Closed by deathau** 2020-11-12 05:07 UTC
Labels: duplicate
