### ISSUE TITLE
Closing a note activates the leftmost note, not an adjacent note

### ISSUE THREAD

**Issue by erichalldev** [deathau/sliding-panes-obsidian#35] opened 2020-12-01 15:55 UTC
When I close a note, I expect the note immediately to the left to be activated.

Instead, the leftmost note is activated.

![sliding-panes-bug](https://user-images.githubusercontent.com/5632228/100763724-2c4bd400-33bb-11eb-9c07-24095ed2da64.gif)

**Comment by yo-goto** [comment] 2020-12-20 11:11
In the stacking mode, it's more troublesome. 
I tend to have many panes. If I close left-side panes , I always have to go back to the left side. Pease fix this problem.
![slidinpaneGo](https://user-images.githubusercontent.com/50942816/102711665-ca69f480-42fe-11eb-9082-a4fd0eedf7b5.gif)

Thanks!

**Comment by pjeby** [comment] 2020-12-26 20:52
This is partly an [Obsidian bug](https://forum.obsidian.md/t/wrong-pane-activates-on-close-of-active-pane-bug-in-getmostrecentleaf/10505), and partly a conflict between this plugin and Obsidian.

This plugin appears to contain some code that tries to work around the problem, or to address a problem in older versions of Obsidian, but that workaround code won't work correctly even after Obsidian fixes the bug.  The issue is that newer versions of Obsidian try to activate the most-recently-used pane after closing one, but this plugin traps that activation and then tries to calculate which pane to activate instead...  and gets it wrong.

AFAICT, this plugin should actually stop trying to guess which pane to activate, as Obsidian now automatically activates the most-recent pane when a pane is closed...  it's just that there's a bug in the `getMostRecentLeaf()` function, causing it to always return the left-most leaf as the "most recent" one!

When that bug is fixed, the logic in this plugin will start activating the wrong leaf.  (I know because I've made a hotfix plugin for the Obsidian bug, and when I watch things in the debugger, closing a pane activates the most-recently-active still-open pane, and then this plugin goes "aha, a pane was removed" and promptly activates the pane to the *left* of the most-recent one instead of leaving well enough alone.)

**Comment by deathau** [comment] 2020-12-30 02:47
I'm removing all the adjacent leaf logic altogether, because Obsidian recently updated to fix this [0.10.3](https://forum.obsidian.md/t/obsidian-release-v0-10-3-insider-build/10605?u=death.au)

> Closing panes will re-focus on the most recent active pane instead of the first pane from the left.

It's not necessarily _adjacent_ as I had (attempted to) implement, but I think it's best to stick to default behaviour in this instance

**Closed** 2020-12-30 02:47 UTC
